# Generated by Django 2.2 on 2024-08-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20240823_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mq',
            name='parts',
        ),
        migrations.AddField(
            model_name='mq',
            name='parts',
            field=models.ManyToManyField(related_name='related_tables', to='shop.Partq'),
        ),
    ]
