# Generated by Django 2.2 on 2024-08-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20240823_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partq',
            name='question',
            field=models.CharField(max_length=1000),
        ),
    ]
