# Generated by Django 2.2 on 2024-08-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_partqa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartqA',
        ),
    ]
