# Generated by Django 2.2 on 2024-08-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20240823_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
