# Generated by Django 2.2 on 2024-08-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_partb_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
            ],
        ),
    ]
