# Generated by Django 2.2 on 2024-08-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20240816_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Users',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
