# Generated by Django 2.2 on 2024-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_partq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainq',
            name='numb',
            field=models.IntegerField(),
        ),
    ]
