# Generated by Django 2.2 on 2024-08-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20240823_0819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MQ',
            new_name='Questions',
        ),
    ]
