# Generated by Django 2.2 on 2024-08-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_delete_partqa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='parts',
        ),
        migrations.AddField(
            model_name='questions',
            name='url',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
