# Generated by Django 2.2 on 2024-08-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_delete_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.IntegerField()),
                ('url', models.CharField(max_length=50)),
                ('ques', models.CharField(max_length=500)),
            ],
        ),
    ]
