# Generated by Django 2.2 on 2024-08-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_partd_parte_partf_partg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
    ]
