# Generated by Django 2.2 on 2024-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_aggrq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partb',
        ),
        migrations.DeleteModel(
            name='Partc',
        ),
        migrations.DeleteModel(
            name='Partd',
        ),
        migrations.DeleteModel(
            name='Parte',
        ),
        migrations.DeleteModel(
            name='Partf',
        ),
        migrations.DeleteModel(
            name='Partg',
        ),
        migrations.DeleteModel(
            name='Partq',
        ),
        migrations.AddField(
            model_name='users',
            name='score',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
