# Generated by Django 2.2 on 2024-08-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20240827_0528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
