# Generated by Django 2.2 on 2024-08-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
