# Generated by Django 2.2 on 2024-08-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20240828_0649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
