# Generated by Django 2.2 on 2024-08-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_scores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scores',
        ),
    ]
