# Generated by Django 2.2 on 2024-08-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_delete_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default=12, max_length=70),
            preserve_default=False,
        ),
    ]
