# Generated by Django 2.2 on 2024-08-30 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
