# Generated by Django 2.2 on 2024-08-30 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='nazar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmm', models.CharField(max_length=400)),
                ('main_q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.MainQ')),
            ],
        ),
    ]
