# Generated by Django 2.2 on 2024-08-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_nazar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nazar',
        ),
    ]
