# Generated by Django 2.2 on 2024-08-31 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0041_delete_nazar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField()),
                ('main_q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.MainQ')),
                ('part_q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.AggrQ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
